# Generated by Django 5.2.14 on 2026-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_poster_thumbnail_file_project_thumbnail_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='poster_file',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
