# Generated by Django 5.2.14 on 2026-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_poster_poster_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
