# Generated by Django 5.2.14 on 2026-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('link', models.URLField(blank=True, max_length=500)),
                ('icon_name', models.CharField(help_text='e.g., Instagram, Linkedin, Mail, Phone', max_length=50)),
                ('color_classes', models.CharField(help_text='Tailwind hover colors and shadows', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Milestone', 'verbose_name_plural': 'Milestones'},
        ),
    ]
