# Generated by Django 5.2.14 on 2026-05-26 13:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_contactchannel_alter_milestone_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactchannel',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='poster',
            name='poster_file',
        ),
        migrations.RemoveField(
            model_name='poster',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='project',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='videoUrl',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='social',
            name='thumbnail_file',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_file',
        ),
        migrations.AddField(
            model_name='poster',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='reel',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='color_classes',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactchannel',
            name='icon_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poster',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='social',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
