# Generated by Django 5.2.14 on 2026-05-27 05:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_contactchannel_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='social',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='reel',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
