# Generated by Django 5.2.14 on 2026-05-27 05:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_poster_thumbnail_remove_reel_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
