# Generated by Django 5.2.14 on 2026-05-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=50)),
                ('trend', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears on the dashboard')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
